Hook open/close notice on the website to CO2 levels instead of a button
hackeriet/hackeriet.no pull request #34
Opened 2021-06-05 23:01 UTC by alexeygridnev

I set up a service on aleksei.hackeriet.no which updates a .json file based on CO2 level in the hackerspace. If over 1000 - someone is there, if below - probably no one is there. Rationale: false positives which happened with the button (I came a couple of times when it was said on the website there was someone in the hackerspace and there was no one). I'll leave it up to you to decide whether you want to use it in addition to, or in combination with, a button.

2021-06-06 10:42 UTC, stigok requested changes

2021-06-06 10:42 UTC, stigok commented on js/hackeriet.js
> +    door.send();
I think this should be `door_co2`

2021-06-06 10:42 UTC, stigok commented on js/hackeriet.js
> +    door_co2.open('GET', 'http://aleksei.hackeriet.no/door.json', true);
This endpoint does not return valid JSON; it uses single quotes instead of double qoutes.

2021-06-06 10:47 UTC, alexeygridnev commented on js/hackeriet.js
> +    door.send();
Sure, you're right

2021-06-06 10:48 UTC, alexeygridnev commented on js/hackeriet.js
> +    door_co2.open('GET', 'http://aleksei.hackeriet.no/door.json', true);
Didn't know it mattered. Will fix it on VM site.

2021-06-06 19:42 UTC, stigok commented
Looks good to me now, but the function isn't currently called anywhere. Are you planning on testing it manually after merge or did you forget to call it?

2021-06-06 19:54 UTC, alexeygridnev commented
I didn't call it deliberately because I want to keep tesing it. Also because the websocket is apparently not working properly (if you look at the website, you'll see it should a constant 7992 value for CO2 on the website, which is not the case on Grafana dashboard).

2021-06-06 21:43 UTC, stigok approved these changes
Ah, I see. Anyway, code looks good :)

2021-06-07 11:56 UTC, fnords commented
I think people should be able to be at Hackeriet without announcing that they are there. I don't think this is a good idea from a privacy standpoint.

2021-06-07 12:05 UTC, atluxity commented
Maybe this could help us avoid the worst of the false positive; That the button is on when there is nobody in the space. That someone is in the space without pushing the button should be allowed.

Do we think the sensing of CO level at all is an issue, or are we just discussing implementation of the synergy effect it can provide?

2021-06-07 13:14 UTC, fnords commented
I realize that the data is already being collected and is available on Grafana, so anyone could in theory monitor if someone is physically at the space now if they wanted to. My initial instinct is that this is a bit creepy, but I think the most important part is that all the members are aware of this.

2021-06-07 20:28 UTC, alexeygridnev commented
We can, of course, use a hybrid approach. If button is pressed AND CO2 level is above normal, then open. Plus, of course it may be a good idea to restrict both the Grafana dashboard and the websocket to members only, with login and password.

2021-06-11 20:16 UTC, alexeygridnev commented on js/hackeriet.js
> +    door_co2.open('GET', 'http://aleksei.hackeriet.no/door.json', true);
Just fixed it on VM side, not there should be correct JSON. Now it remains to fix websocket itself so that it gives the correct CO2 and tVOC values rather than constant 7992 and 1156 respectively

2021-06-19 18:46 UTC, stigtsp commented on js/hackeriet.js
> +        if(this.status >= 200 && this.status < 400) {
are you expecting any other status-code than 200?

2021-06-19 18:50 UTC, merged