Add picture of the door
hackeriet/hackeriet.no pull request #46
Opened 2022-07-09 20:27 UTC by kiloreven

2022-08-02 13:01 UTC, stigok requested changes
Please update the english version as well if you don't mind :)

2022-08-02 13:01 UTC, stigok commented on index.no.html
> +    <a href="images/hackeriet-door.png"><img class="thumbnail" src="images/hackeriet-door_thumb.png" alt="Hackeriet" width="400"></a> <br />
Can you update the alt-text sto say that this is the "Hackeriet main door" or something similar?

2022-08-02 15:23 UTC, stigtsp commented on index.no.html
> +    <a href="images/hackeriet-door.png"><img class="thumbnail" src="images/hackeriet-door_thumb.png" alt="Hackeriet" width="400"></a> <br />
Missing for `index.en.html` ?

2024-08-23 16:59 UTC, sjn commented
Merge? :)

2024-08-23 17:05 UTC, stigtsp commented
> Merge? :)

Feedback has not been resolved yet

2025-09-10 14:47 UTC, merged